name: damascus_institute
description: "تطبيق المعهد التقاني للحاسوب - جامعة دمشق فرع درعا"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.5.0
  provider: ^6.1.2
  flutter_dotenv: ^6.0.1
  table_calendar: ^3.1.2
  fl_chart: ^1.2.0
  flutter_local_notifications: ^22.0.1      # تحديث هام
  intl: 0.20.2
  font_awesome_flutter: ^11.0.0
  excel: ^4.0.0
  file_picker: ^8.3.7
  device_info_plus: ^13.2.0                 # تحديث هام
  package_info_plus: ^10.2.0                # تحديث هام
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#0F172A"
    theme_color: "#3B82F6"